### ISSUE TITLE
TrickOps: yaml config validation isn't robust for run directories/many/layers/deep

### ISSUE THREAD

**Issue by ddj116** [nasa/trick#1159]
## The problem

The duplicate run logic checking for `parallel_safety: strict` will fail in the following example:

```
SIM_foo:
  path: path/to/SIM_foo
  runs:
    RUN_bar/input.py:
    studies/RUN_bar/input.py:
```

This is due to non-robust path checking logic in `share/trick/trickops/TrickWorkflow.py` near line 387.  Additionally I noticed that there's no checking for duplicate `valgrind` `runs:` entries. 

## The solution

Move to `os.path.dirname()` like I should have done in the first place, add the similar checks for valgrind, and update the unit tests to cover this use-case.
