### ISSUE TITLE
TrickOps: Support execution of MonteCarloGeneration use cases

### ISSUE THREAD

**Issue by ddj116** [nasa/trick#1391]
## Summary & Background

As referenced [in code here](https://github.com/nasa/trick/blob/master/share/trick/trickops/TrickWorkflow.py#L1471), TrickOps currently does not support monte-carlo in any way:

```
    TODO: This is not currently tested or supported by the TrickWorkflow
    management layer. However, this class has been used in a project in
    the 2017-2020 timeframe and should still be functional. Reason for
    not currently supporting it is mostly because the biggest users of
    Trick monte-carlo have already moved away from it's internal master/
    slave architecture so there isn't much of a need.
```
With the verified ramtares-born CML monte-carlo [getting close to being ready](https://github.com/nasa/trick/pull/1389), I'd like to improve TrickOps to support execution of generated runs from this framework.  In this issue I'd like to discuss design options and settle on an approach before implementing it.

Note that in this issue "monte-carlo" implies "CML monte-carlo" exclusively. We do not intend to support old-style master-slave monte-carlo.

## Requirements

Here's a list of requirements of the new monte-carlo capabilities. Looking for input/feedback on this list and everything else. `?` means I'm not sure if it should be included.

1. Local generation of runs with monte-carlo enabled - just running `./S_main... RUN...` for a run configured with monte-carlo enabled
2. Local execution of generated runs - just running `./S_main... MONTE_RUN.../RUN*/monte_input.py` after (1)
3. YAML file must understand monte-carlo generation, and monte-carlo generated runs, supporting (1) and (2) with the following capabilities:
    1. Execution of a subset of the generated runs?
    2. Specification of expected return code(s) of generated runs?
    3. `analyze`: supported per-MONTE-set (a VERAS report for example)
    4. `analyze`: supported per-run?
    5. `compare`: supported per-run?
    6. `compare`: supported per-MONTE-set?
 4. TBD more requirements go here

## The YAML File

We must modify the fields the YAML file can understand to support this capability. There are a few options on how we would let the user specify monte-carlo runs, and we'll have to settle on one.  Here' are some options:

### Option 1 - Modify `run:` to have a `monte_carlo` flag that defaults to `False`

```yaml
  runs:
    studies/SET_monte/RUN_rcs_jets/input.py --mc_num_runs=100 --monte_dir=<some/path>:
      monte_carlo: one of three options
        <path-glob>  <-- means "run resulting generated runs after generation complete at this glob-path"
        True         <-- means "generate runs but don't run them"
        False        <-- default, this is a normal non-monte-carlo run
```
Notes:
  * Doesn't support specification/execution of subset of generated runs - all runs must be run
  * Supports non-zero expected return code for generation, but not generated runs
  * TrickOps may not know how many runs were expected -  "what I found via glob is all I know"
  * `--monte_dir` and `--mc_num_runs` cmd-line args are not required, this is just a common usage (ramtares)
  * `compare` works the same way as a normal RUN, the user must specify all generated runs manually if they want to compare them

### Option 2 - Create a new sim-level entry `mc_runs:` which describes generation and generated content
```yaml
  mc_runs:
    studies/SET_monte/RUN_rcs_jets/input.py --mc_num_runs=100 --monte_dir=<some/path>:
      output_dir: <relative or absolute path>    <-- (optional) path to generated runs
      expected_runs: <non-zero int>              <-- (optional) Expected number of generated runs
      generation_returns: <int>                  <-- (optional) what generation is expected to return
      generated_returns: [0, 0, 1, ... ]         <-- (optional) list of len(expected_runs) of ints
```
Notes:
  * Doesn't support specification/execution of subset of generated runs - all runs must be run
  * Supports expected return codes for generation and generated runs
  * `compare` works the same way as a normal RUN, the user must specify all generated runs manually if they want to compare them

### Option 3 - The generation of runs lives in `runs:`, generated runs live in new `mc_runs`, support `[XXXX-YYYY]` pattern matching

```yaml
  runs:
    studies/SET_monte/RUN_rcs_jets/input.py --mc_num_runs=100 --monte_dir=<some/path>:
  mc_runs:
    studies/SET_monte/MONTE_RUN_rcs_jets/RUN_0000:
      returns: 0
    studies/SET_monte/MONTE_RUN_rcs_jets/RUN_0001:
      returns: 0
    studies/SET_monte/MONTE_RUN_rcs_jets/RUN_[XXXX-YYYYY]:
      returns: 0
      compare:
        studies/SET_monte/MONTE_RUN_rcs_jets/RUN_[000-079]/foo.csv vs. baseline/studies/SET_monte/MONTE_RUN_rcs_jets/RUN_[000-079]/foo.csv
        studies/SET_monte/MONTE_RUN_rcs_jets/RUN_090/foo.csv vs. baseline/studies/SET_monte/MONTE_RUN_rcs_jets/RUN_090/foo.csv
```
Notes:
  * Run generation is a "normal `run:`", it's just an single RUN execution. No cross `runs:`/`mc_runs:` checking, which requires the user to put the full configuration under two headings. This may also cause confusion when the user wants to ask TrickOps for "the runs that generate runs".
  * Supports explicit specification/execution of subset of generated runs
  * Supports expected return codes for generation and generated runs
  * Similar in style to `runs:`, where runs are explicitly listed
  * Supports pattern expansion `[XXXX-YYYY]` which is highly configurable but complex to implement. Is there a library for this we could leverage? Should this be available in `runs:` too?
  * `compare` works the same way as a normal RUN, the user must specify all generated runs manually if they want to compare them

### Option 4 - Other ideas go here. Maybe Option 2's YAML syntax with Option 3's pattern expansion?

TBD

### Notes common to all approaches

1. With Trick and monte-carlo supporting the configuration of where `MONTE_RUN../RUN_XYZ` are written to, the writer of the YAML file must know this information that may be hidden behind the input file configuration. Additionally, if the use-case uses `--monte-dir` on the `./S_main...` cmd-line, this output dir would need to be updated in two places in the YAML file.
2. How much error checking should TrickOps do wrt generated runs? They may or may not exist at YAML processing time.
3. Should TrickOps provide a check for "do generated runs exist?" to skip generation phase if the user wants? Or is that on the user?

---

FYI @jdeans289 @jmpenn @spfennell - this issue is definitely a work in progress and I'm looking for feedback on the design before implementing anything. I'll swing by sometime this afternoon to start the conversation.

**Comment by ddj116** [comment]
Thanks everybody for the productive discussion yesterday! Walking in to work this morning, I starting wondering if @jdeans289 's idea for supporting RUN "phasing" for testing checkpoint-restart could also support this monte-carlo use case. Consider Option 4...

### Option 4 - Implement `run:` phasing and `[XXXX-YYYY]` pattern matching giving the `run:` subsection all the features needed to support monte-carlo and checkpoint-restart

Consider a YAML file that looks like this:

```yaml
  runs:
    RUN_nominal/input.py:                <-- normal (non-monte-carlo) run
      phase: 0
    RUN_checkpoint_dump/input.py:        <-- normal run that dumps a checkpoint
      phase: 0
    RUN_checkpoint_load/input.py:        <-- normal run that loads the dumped checkpoint
      phase: 1
    RUN_monte/input.py --mc_num_runs=100:  <-- monte-carlo generation run
      phase: 0
    MONTE_RUN_monte/RUN_0000/monte_input.py: <-- One generated run expected to return 0
      phase: 1
      returns: 0
      exists: False
    MONTE_RUN_monte/RUN_0001/monte_input.py: <-- One generated run expected to return 1
      phase: 1
      returns: 1
      exists: False
      analyze: ./process/a/single/run.py
    MONTE_RUN_monte/RUN_[XXXX-YYYY]/monte_input.py:  <-- pattern matched range covers many runs
      phase: 1
      returns: 0
      exists: False
      compare:
        MONTE_RUN_monte/RUN_[XXXX-YYYY]/foo.csv vs. baseline/MONTE_RUN_monte/RUN_[XXXX-YYYY]/foo.csv
      analyze: ./process/a/subset/of/runs.py
```

This would add two new `run:` attributes, and the documentation would be modified to something like this:
```yaml
#   runs:                <-- optional dict of runs to be executed for this sim, where the
#     RUN_1/input.py --foo:  dict keys are the literal arguments passed to the sim binary
#     RUN_2/input.py:        and the dict values are other run-specific optional dictionaries
#     RUN_[3-9]/input.py:    described below. Integer zero-padded ranges are supported inside
#       ...                  [] to define attributes for multiple sets of runs matching this
#       ...                  numeric pattern (ex: monte-carlo generated runs)
#       ...
#       returns: <int>   <---- optional expected exit code of this run upon completion (0-255).
#                              Defaults to 0
#       phase: <int>     <-- optional integer within range (-1000, 1000) describing phase in
#                            which this run should execute. Defaults to 0, but allows runs to
#                            be ordered before or after other runs (monte-carlo, checkpoint, etc)
#       exists: <True|False>  <-- optional check for input file existence when this YAML is
#                                 processed. Defaults to True
#       compare:         <---- optional list of <path> vs. <path> comparison strings to be
#         - a vs. b            compared after this run is complete. This is extensible in that
#         - d vs. e            all non-list values are ignored and assumed to be used to define
#         - ...                an alternate comparison method in a class extending this one
#       analyze:         <-- optional arbitrary string to execute as job in bash shell from
#                            project top level, for project-specific post-run analysis
```

Notes:

-  In this approach TrickOps knows nothing about monte-carlo, it only knows about phases and whether or not runs should be checked for existence when the YAML is processed. All runs in phase 0 run before all runs in phase 1, and so on. Both new options `phase` and `exists` are optional, and if not specified, runs act as they do today.
- `[XXXX-YYYY]` pattern matching is similar to glob notation in functionality, specifics of the syntax/capabilities still TBD, but at minimum zero-padded numeric ranges are supported.

One thing I like about this approach is that it provides a simple capability addition that suits both checkpoint-restart and monte-carlo use cases. It also does not create any dependencies on MonteCarloGenerate, it just happens to work with the output MonteCarloGenerate provides - it's an interface match without requiring any inheritance or separate modules.  Curious to hear your opinions on this idea @jdeans289 @spfennell @jmpenn
